version: "3"

dotenv:
  - .env

tasks:
  test:
    method: none
    sources:
      - "**/*.go"
    cmds:
      - go test -run {{default "''" .GO_TEST_FILTER}} {{.GO_TEST_FLAGS}} {{default "./..." .CLI_ARGS}}
